---
abstract: 'Parse and manipulate Perl version strings'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires:
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Version
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Data::Dumper: '0'
  File::Slurp::Tiny: '0'
  Getopt::Long: '2.34'
  Pod::Usage: '1.3'
  Scalar::Util: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/Perl--Version/issues
  homepage: https://github.com/briandfoy/Perl--Version
  repository: https://github.com/briandfoy/Perl--Version.git
version: 1.013_03
